### ISSUE TITLE
Zero block detection

### ISSUE THREAD

**Issue by TimJDFletcher** [TargetHolding/bdsync#4]
Carrying on setting up my backup process another request. Would it be possible to include zero block detection, I am syncing two thin provisioned volumes so the last section of the disks are all zeros. Currently bdsync is thrashing the CPU on both the source and the target checksumming large blocks of zeros.

**Comment by rolffokkens** [comment]
Might not be hard to do, I'll look into this.

**Comment by rolffokkens** [comment]
Due to the streaming nature of disk reading / hash generation it appears to be somewhat harder than I thought. Yet not giving up.

**Comment by TimJDFletcher** [comment]
Googling this over coffee this morning, I found this: http://stackoverflow.com/questions/6938219/how-to-check-whether-all-bytes-in-a-memory-block-are-zero

**Comment by rolffokkens** [comment]
There's a new --zeroblocks option which makes bdsync identify zero blocks and handle them more efficient. Could you try?

**Comment by TimJDFletcher** [comment]
It does indeed, looking at it on my desktop with bdsync running on 2 different cores it looks to be about 30% CPU saving running on completely sparse file.

I've written a test script as well for it. The test is for a 10G sparse file.

**** Checking: --zeroblock speed test
  |  no --zeroblock set
  |  
  |  real	0m28.076s
  |  user	0m22.458s
  |  sys	0m5.493s
  |  --zeroblock set on remote
  |  
  |  real	0m42.825s
  |  user	0m26.541s
  |  sys	0m16.159s
  |  --zeroblock set on local
  |  
  |  real	0m45.030s
  |  user	0m9.714s
  |  sys	0m21.645s
  |  --zeroblock set on both
  |  
  |  real	0m11.358s
  |  user	0m4.612s
  |  sys	0m6.662s

**Comment by rolffokkens** [comment]
Thanks, included the performance test in bdsync.

The results of the performance test are weird: bdsync apparently needs more elapsed/CPU time when local and remote don't make the same choice for --zeroblocks. I can reproduce here. It suggests some kind of busy wait which is definitely not the intention!

**Comment by TimJDFletcher** [comment]
When I was running some of the tests I noticed that time reported quite large differences in the number of context switches between --zeroblock set and not set. I'm rerunning test9 with more verbose time options set to see if that is the difference.

**Comment by TimJDFletcher** [comment]
**** Checking: --zeroblock speed test
  |  no --zeroblock set
  |  24.52user 6.37system 0:31.60elapsed 97%CPU (0avgtext+0avgdata 43604maxresident)k
  |  0inputs+0outputs (0major+10472minor)pagefaults 0swaps
  |  --zeroblock set on remote
  |  26.78user 16.38system 0:43.28elapsed 99%CPU (0avgtext+0avgdata 1070236maxresident)k
  |  448inputs+0outputs (9major+267423minor)pagefaults 0swaps
  |  --zeroblock set on local
  |  10.40user 22.13system 0:45.60elapsed 71%CPU (0avgtext+0avgdata 325860maxresident)k
  |  328inputs+0outputs (2major+2468156minor)pagefaults 0swaps
  |  --zeroblock set on both
  |  4.50user 5.65system 0:10.26elapsed 98%CPU (0avgtext+0avgdata 43616maxresident)k
  |  392inputs+0outputs (3major+10461minor)pagefaults 0swaps
--> PASS

**Comment by TimJDFletcher** [comment]
That is the results from the different test, if you look at the massive increase in context switches when --zeroblock is not set the same at both ends.

**Comment by TimJDFletcher** [comment]
I've pushed test9 with the more verbose version of time to my tree if you want to test it locally

**Comment by rolffokkens** [comment]
There's is clear bug, probable related: Apparently with mixed --zeroblocks settings matching of zero blocks between local and remote fails resulting in large bdsync files. I should look into that, and create a test for this.

**Comment by TimJDFletcher** [comment]
You can adapt the 10GB sparse test drop the test to say 100MB. The diff file should be close to 0 bytes allowing for headers.

**Comment by rolffokkens** [comment]
Found it: I forgot to salt the zeroblock-cache. Will fix it shortly.

**Comment by rolffokkens** [comment]
Fixed id. Timing makes sense now:
**** Checking: --zeroblocks speed test
  |  no --zeroblocks set
  |  
  |  real	0m29.287s
  |  user	0m22.327s
  |  sys	0m3.861s
  |  --zeroblocks set on remote
  |  
  |  real	0m27.187s
  |  user	0m22.586s
  |  sys	0m3.791s
  |  --zeroblocks set on local
  |  
  |  real	0m26.324s
  |  user	0m8.956s
  |  sys	0m3.357s
  |  --zeroblocks set on both
  |  
  |  real	0m13.986s
  |  user	0m8.897s
  |  sys	0m3.695s
--> PASS

**Comment by rolffokkens** [comment]
BTW Thanks for input! Was very helpful!

**Comment by TimJDFletcher** [comment]
Glad it was helpful not just nagging, you've helped fix a backup replication problem I was having.

Oh I'm getting compile errors on Ubuntu 14.10 and 15.04, it's something simple but I don't know c well enough to fix it.

tim@desktop-tim:/usr/src/git/bdsync$ make
cc -Wall -O3 -lcrypto -o bdsync bdsync.c checkzero.c
bdsync.c: In function ‘init_salt’:
bdsync.c:362:9: warning: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Wunused-result]
         read (fd, salt, saltsize);
         ^
bdsync.c: In function ‘send_block’:
bdsync.c:979:5: warning: ignoring return value of ‘pread’, declared with attribute warn_unused_result [-Wunused-result]
     pread (fd, cp, len, pos);
     ^
/tmp/ccVFNxKi.o: In function `find_zero_hash':
bdsync.c:(.text+0x5fb): undefined reference to `EVP_get_digestbyname'
bdsync.c:(.text+0x60f): undefined reference to `EVP_MD_size'
bdsync.c:(.text+0x618): undefined reference to `EVP_MD_CTX_create'
bdsync.c:(.text+0x628): undefined reference to `EVP_DigestInit_ex'
bdsync.c:(.text+0x67d): undefined reference to `EVP_DigestUpdate'
bdsync.c:(.text+0x68f): undefined reference to `EVP_DigestUpdate'
bdsync.c:(.text+0x6a4): undefined reference to `EVP_DigestFinal_ex'
bdsync.c:(.text+0x6ac): undefined reference to `EVP_MD_CTX_destroy'

**Comment by rolffokkens** [comment]
Ouch. I think I fixed it. Could you try again?

**Comment by TimJDFletcher** [comment]
Builds and passes all tests, I still get a warning of:

tim@desktop-tim:/usr/src/git/bdsync$ make
cc -Wall -O3  -o bdsync bdsync.c checkzero.c -lcrypto
bdsync.c: In function ‘send_block’:
bdsync.c:984:5: warning: ignoring return value of ‘pread’, declared with attribute warn_unused_result [-Wunused-result]
     pread (fd, cp, len, pos);

**Comment by rolffokkens** [comment]
I think the warning is fixed now, but I'm creating an Ubuntu container to test it myself.

**Comment by TimJDFletcher** [comment]
It's fixed on my Ubuntu-15.04 system no compile warnings at all
